apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::245801612153:role/UdacityFlaskDeployCBKubectlRole
      username: build    
      groups:
        - system:masters 

    - rolearn: arn:aws:iam::245801612153:root
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::245801612153:root\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2022-10-17T12:10:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3545"
  uid: 62cad37a-9b96-4a1a-85e0-72f58bd51002
