apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::245801612153:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R660820JSJZE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::245801612153:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-17T14:03:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1628"
  uid: 20bebfea-d3e5-4edc-94f2-d7bc8260565a
